In [77]:
import plotly
import plotly.express as px
import pandas as pd

In [78]:
countries_path = r'C:\Users\35192\Desktop\Tese\Criar Base de Dados\Base_Dados.csv'

In [79]:
df = pd.read_csv(countries_path)
df

,NúmeroCaso,Ano,Data,Hora_UTC,Período,lat_d,lon_d,Estado_Costeiro,Resumo,iso_alpha,...,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48
0,#VALUE!,2015,12/5/2015,1:39,Noturno,-4.750000,11.783333,Congo,Three robbers boarded the anchored ship via th...,COG,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,#VALUE!,2016,7/7/2016,6:50,Diurno,3.266667,5.150000,Nigéria,Armed pirates approached and fired upon the ta...,NGA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,#VALUE!,2008,1/14/2008,0:44,Noturno,-8.715000,13.313333,Angola,Two robbers boarded the ship from a small boat...,AGO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,#VALUE!,2008,1/23/2008,5:20,Noturno,-8.770000,13.273333,Angola,"Pirates boarded the ship, broke open the forwa...",AGO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,#VALUE!,2010,8/31/2010,1:10,Noturno,-5.873333,13.031667,Angola,Three robbers armed with knives in a boat boar...,AGO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
655,495,2018,5/21/2018,22:55,Noturno,3.766667,1.500000,Togo,An attempt was made by one individual to board...,TGO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
656,496,2019,3/3/2019,19:40,Noturno,5.866667,1.400000,Togo,Armed pirates attack and boarded a tanker\nund...,TGO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
657,497,2019,11/4/2019,2:40,Noturno,5.970333,1.261667,Togo,Three persons armed with guns and knives\nboar...,TGO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
658,498,2020,3/5/2020,7:30,Diurno,5.370000,1.600000,Togo,Master onboard the tanker underway noticed a\n...,TGO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
659,499,2020,10/17/2020,17:10,Diurno,4.233333,-1.400000,Togo,"While underway, perpetrators armed with guns a...",TGO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [84]:
map_fig = px.scatter_geo(df,
                         locations = 'iso_alpha',
                         projection = 'orthographic',
                         color = 'Ano',
                         opacity = .8,
                         hover_name = 'Ano',
                         hover_data = ['Data', 'Estado_Costeiro']
                        )

In [85]:
plotly.offline.plot(map_fig, filename = 'C:\map_exp.html', )

PermissionError: [Errno 13] Permission denied: 'C:\\map_exp.html'